/**
 * script.js for the DJ Sharkboy website
 *
 * DYNAMIC ASSET SYSTEM
 * ─────────────────────
 * All media is loaded from assets/manifest.json (generated by generate-manifest.js).
 *
 * Folder rules (edit content by dropping files in/out, then re-run generate-manifest.js):
 *   assets/hero/           -> one hero background is picked at random
 *   assets/about/          -> about section media
 *   assets/gallery-photos/ -> curated photo carousel
 *   assets/gallery-videos/ -> video reel
 *
 * Static assets (logos etc.) go in assets/static/ and are referenced directly in HTML/CSS.
 */

// ─── Utilities ───────────────────────────────────────────────────────────────

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ─── Site Loader ────────────────────────────────────────────────────────────
// The actual hideLoader logic is inline in index.html to guarantee it runs fast.
function hideLoader() {
  if (window.__hideLoader) window.__hideLoader();
}

// ─── Nav scroll effect ────────────────────────────────────────────────────────

window.addEventListener('scroll', () => {
  document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 30);
}, { passive: true });

// ─── Mobile menu ─────────────────────────────────────────────────────────────

document.querySelector('.nav-toggle').addEventListener('click', (event) => {
  const isOpen = document.getElementById('mobileMenu').classList.toggle('open');
  event.currentTarget.setAttribute('aria-expanded', String(isOpen));
});

function closeMobile() {
  document.getElementById('mobileMenu').classList.remove('open');
  document.querySelector('.nav-toggle').setAttribute('aria-expanded', 'false');
}

// ─── Gigs tabs ────────────────────────────────────────────────────────────────

document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('tab-' + btn.dataset.tab).classList.add('active');
  });
});

// ─── Scroll reveal ────────────────────────────────────────────────────────────

(function initReveal() {
  const obs = new IntersectionObserver((entries) => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); } });
  }, { threshold: 0.1 });

  document.querySelectorAll('.section-intro, .service-card, .gig-card, .about-text, .section-heading, .booking-wrap').forEach((el, index) => {
    el.classList.add('reveal');
    el.style.transitionDelay = `${Math.min(index % 3, 2) * 70}ms`;
    obs.observe(el);
  });

})();

// ─── Subtle hero parallax ────────────────────────────────────────────────────

if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
  window.addEventListener('scroll', () => {
    const hero = document.getElementById('hero');
    const image = document.getElementById('heroBg');
    if (!hero || !image || window.scrollY > hero.offsetHeight) return;
    image.style.backgroundPosition = `center calc(50% + ${window.scrollY * 0.08}px)`;
  }, { passive: true });
}

// ─── Carousel builder ─────────────────────────────────────────────────────────

/**
 * buildCarousel(config)
 *
 * config.trackEl    - the .carousel-track element
 * config.dotsEl     - the .carousel-dots element
 * config.arrowLeft  - left arrow button
 * config.arrowRight - right arrow button
 * config.slides     - array of DOM elements
 */
function buildCarousel({ trackEl, dotsEl, arrowLeft, arrowRight, slides }) {
  if (!slides.length) return;

  const wrapEl = trackEl.parentElement;
  slides.forEach(slide => trackEl.appendChild(slide));

  let current = 0;
  let currentOffset = 0;
  let startX = 0;
  let startOffset = 0;
  let pointerId = null;
  let moved = false;
  let resizeFrame = null;
  const total = slides.length;

  slides.forEach((_, i) => {
    const dot = document.createElement('button');
    dot.type = 'button';
    dot.className = 'dot' + (i === 0 ? ' active' : '');
    dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
    dot.addEventListener('click', () => goTo(i));
    dotsEl.appendChild(dot);
  });

  function positionFor(idx) {
    const slide = slides[idx];
    return (wrapEl.clientWidth / 2) - (slide.offsetLeft + slide.offsetWidth / 2);
  }

  function renderOffset(offset, animate = true) {
    currentOffset = offset;
    trackEl.classList.toggle('is-dragging', !animate);
    trackEl.style.transform = `translate3d(${offset}px, 0, 0)`;
  }

  function goTo(idx, animate = true) {
    current = Math.max(0, Math.min(idx, total - 1));
    renderOffset(positionFor(current), animate);

    slides.forEach((s, i) => s.classList.toggle('is-active', i === current));
    dotsEl.querySelectorAll('.dot').forEach((d, i) => d.classList.toggle('active', i === current));
    arrowLeft.disabled = current === 0;
    arrowRight.disabled = current === total - 1;
  }

  arrowLeft.addEventListener('click', () => goTo(current - 1));
  arrowRight.addEventListener('click', () => goTo(current + 1));

  wrapEl.addEventListener('pointerdown', event => {
    if (event.button !== 0 || event.target.closest('button')) return;
    pointerId = event.pointerId;
    startX = event.clientX;
    startOffset = currentOffset;
    moved = false;
    wrapEl.setPointerCapture(pointerId);
    wrapEl.classList.add('is-dragging');
    renderOffset(currentOffset, false);
  });

  wrapEl.addEventListener('pointermove', event => {
    if (event.pointerId !== pointerId) return;
    const delta = event.clientX - startX;
    if (Math.abs(delta) > 6) moved = true;
    renderOffset(startOffset + delta, false);
  });

  function finishDrag(event) {
    if (event.pointerId !== pointerId) return;
    const delta = event.clientX - startX;
    pointerId = null;
    wrapEl.classList.remove('is-dragging');
    if (delta < -55) goTo(current + 1);
    else if (delta > 55) goTo(current - 1);
    else goTo(current);
  }

  wrapEl.addEventListener('pointerup', finishDrag);
  wrapEl.addEventListener('pointercancel', finishDrag);
  wrapEl.addEventListener('click', event => {
    if (!moved) return;
    event.preventDefault();
    event.stopPropagation();
    moved = false;
  }, true);

  window.addEventListener('resize', () => {
    cancelAnimationFrame(resizeFrame);
    resizeFrame = requestAnimationFrame(() => goTo(current, false));
  }, { passive: true });

  requestAnimationFrame(() => goTo(0, false));
}

// ─── Video lightbox ───────────────────────────────────────────────────────────

const lightbox     = document.getElementById('videoLightbox');
const lightboxVid  = document.getElementById('lightboxVideo');
const lightboxClose = document.getElementById('lightboxClose');

function openLightbox(src) {
  lightboxVid.src = src;
  lightbox.classList.add('open');
  lightboxVid.play();
}

function closeLightbox() {
  lightbox.classList.remove('open');
  lightboxVid.pause();
  lightboxVid.src = '';
}

lightboxClose.addEventListener('click', closeLightbox);
lightbox.addEventListener('click', e => { if (e.target === lightbox) closeLightbox(); });
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeLightbox(); });

// ─── Dynamic asset loader (reads manifest.json) ───────────────────────────────

fetch('assets/manifest.json?v=' + Date.now())
  .then(r => r.json())
  .then(manifest => {
    let tasksToWait = [];

    // ── HERO background (random pick from assets/hero/) ──────────────────────
    const heroFiles = manifest['hero'] || [];
    if (heroFiles.length) {
      const heroBg  = document.getElementById('heroBg');
      const heroSrc = pickRandom(heroFiles);
      const p = new Promise(resolve => {
        const img = new Image();
        img.onload = () => {
          heroBg.style.backgroundImage = `url('${heroSrc}')`;
          requestAnimationFrame(() => heroBg.classList.add('loaded'));
          resolve();
        };
        img.onerror = resolve; // Continue even if it fails
        img.src = heroSrc;
      });
      tasksToWait.push(p);
    }

    // ── ABOUT photo (replaced by static video) ─────────────────────────
    // The video is now statically embedded in index.html

    // Curate distinct scenes and crops so the gallery does not feel repetitive.
    const preferredPhotoNames = [
      'gallery-orange-performance.jpg',
      'gallery-crowd-wide.jpg',
      'gallery-green-motion.jpg',
      'gallery-action-wide.jpg',
      'gallery-laughing.webp',
      'gallery-artistic.webp',
      'gallery-mic-purple.webp',
      'gallery-headphones.webp',
      'gallery-shark-1.webp',
    ];
    const photoAltText = {
      'gallery-orange-performance.jpg': 'DJ Sharkboy performing under orange stage lights',
      'gallery-crowd-wide.jpg': 'DJ Sharkboy facing the dance floor during a club set',
      'gallery-green-motion.jpg': 'DJ Sharkboy moving to the music behind the decks',
      'gallery-action-wide.jpg': 'DJ Sharkboy mixing live with the crowd in front',
      'gallery-laughing.webp': 'DJ Sharkboy smiling during a live event',
      'gallery-artistic.webp': 'Creative portrait of DJ Sharkboy',
      'gallery-mic-purple.webp': 'DJ Sharkboy hosting with a microphone',
      'gallery-headphones.webp': 'DJ Sharkboy wearing headphones at the decks',
      'gallery-shark-1.webp': 'DJ Sharkboy performing live',
    };
    const allPhotoFiles = manifest['gallery-photos'] || [];
    const photoFiles = preferredPhotoNames
      .map(name => allPhotoFiles.find(src => src.endsWith('/' + name)))
      .filter(Boolean);

    if (photoFiles.length) {
      const slides = photoFiles.map((src, index) => {
        const div = document.createElement('div');
        div.className = 'photo-slide';
        const img = document.createElement('img');
        const fileName = src.split('/').pop();
        const markOrientation = () => {
          div.classList.toggle('is-landscape', img.naturalWidth > img.naturalHeight);
        };
        
        if (index < 2) {
           const p = new Promise(res => {
             img.onload = () => { markOrientation(); res(); };
             img.onerror = res;
             img.src = src;
           });
           tasksToWait.push(p);
        } else {
           img.addEventListener('load', markOrientation, { once: true });
           img.src = src;
           img.loading = 'lazy';
        }

        img.alt = photoAltText[fileName] || 'DJ Sharkboy at a live event';
        div.appendChild(img);
        return div;
      });

      buildCarousel({
        trackEl:    document.getElementById('photoTrack'),
        dotsEl:     document.getElementById('photoDots'),
        arrowLeft:  document.getElementById('photoArrowLeft'),
        arrowRight: document.getElementById('photoArrowRight'),
        slides,
      });
    }

    // ── VIDEO REEL (all from assets/gallery-videos/) ──────────────────────────
    const videoFiles = manifest['gallery-videos'] || [];
    if (videoFiles.length) {
      const slides = videoFiles.map((src, index) => {
        const div = document.createElement('div');
        div.className = 'video-slide';

        const vid = document.createElement('video');
        vid.muted = true;
        vid.loop  = true;
        vid.playsInline = true;
        vid.preload = 'metadata';

        if (index < 2) {
           const p = new Promise(res => {
             vid.onloadedmetadata = res;
             vid.onerror = res;
             vid.src = src;
           });
           tasksToWait.push(p);
        } else {
           vid.src = src;
        }

        div.addEventListener('mouseenter', () => vid.play().catch(()=>{}));
        div.addEventListener('mouseleave', () => { vid.pause(); vid.currentTime = 0; });

        const overlay = document.createElement('div');
        overlay.className = 'video-play-btn';
        const btn = document.createElement('span');
        btn.innerHTML = '&#9654;';
        overlay.appendChild(btn);

        div.addEventListener('click', () => openLightbox(src));

        div.appendChild(vid);
        div.appendChild(overlay);
        return div;
      });

      buildCarousel({
        trackEl:    document.getElementById('videoTrack'),
        dotsEl:     document.getElementById('videoDots'),
        arrowLeft:  document.getElementById('videoArrowLeft'),
        arrowRight: document.getElementById('videoArrowRight'),
        slides,
      });
    }

    Promise.all(tasksToWait).then(() => {
      hideLoader();
    });

  })
  .catch(err => {
    console.warn('Could not load manifest.json — run generate-manifest.js first.', err);
    hideLoader();
  });

// ─── Booking form (mailto fallback) ──────────────────────────────────────────

document.getElementById('bookingForm').addEventListener('submit', function (e) {
  e.preventDefault();
  const d = new FormData(this);
  const subject = encodeURIComponent('Booking Enquiry: ' + d.get('eventType'));
  const body    = encodeURIComponent(
    `Name: ${d.get('name')}\nEmail: ${d.get('email')}\nEvent: ${d.get('eventType')}\nDate: ${d.get('eventDate')}\nService: ${d.get('service')}\n\nDetails:\n${d.get('message')}`
  );
  window.location.href = `mailto:sharkboyrecords@gmail.com?subject=${subject}&body=${body}`;
});
