/**
 * script.js — DJ Sharkboy website
 *
 * DYNAMIC ASSET SYSTEM
 * ─────────────────────
 * All media is loaded from assets/manifest.json (generated by generate-manifest.js).
 *
 * Folder rules (edit content by dropping files in/out, then re-run generate-manifest.js):
 *   assets/hero/           → hero background — 1 picked at random each load
 *   assets/about/          → about section photo — 1 picked at random each load
 *   assets/gallery-photos/ → photo carousel — ALL files shown in order
 *   assets/gallery-videos/ → video reel — ALL files shown in order
 *
 * Static assets (logos etc.) go in assets/static/ and are referenced directly in HTML/CSS.
 */

// ─── Utilities ───────────────────────────────────────────────────────────────

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ─── Nav scroll effect ────────────────────────────────────────────────────────

window.addEventListener('scroll', () => {
  document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 60);
});

// ─── Mobile menu ─────────────────────────────────────────────────────────────

document.querySelector('.nav-toggle').addEventListener('click', () => {
  document.getElementById('mobileMenu').classList.toggle('open');
});

function closeMobile() {
  document.getElementById('mobileMenu').classList.remove('open');
}

// ─── Gigs tabs ────────────────────────────────────────────────────────────────

document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('tab-' + btn.dataset.tab).classList.add('active');
  });
});

// ─── Wave canvas animation (hero) ────────────────────────────────────────────

(function initWave() {
  const canvas = document.getElementById('waveCanvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');

  function resize() { canvas.width = canvas.offsetWidth; canvas.height = canvas.offsetHeight; }
  resize();
  window.addEventListener('resize', resize);

  const waves = [
    { y: 0.55, amp: 28, freq: 0.012, speed: 0.018, color: 'rgba(30,106,255,0.2)',  offset: 0 },
    { y: 0.63, amp: 20, freq: 0.016, speed: 0.024, color: 'rgba(30,106,255,0.13)', offset: 2 },
    { y: 0.70, amp: 16, freq: 0.020, speed: 0.014, color: 'rgba(255,138,32,0.10)', offset: 4 },
    { y: 0.50, amp: 12, freq: 0.009, speed: 0.010, color: 'rgba(30,106,255,0.08)', offset: 6 },
  ];

  let t = 0;
  function drawWave(w) {
    const W = canvas.width, H = canvas.height;
    ctx.beginPath(); ctx.moveTo(0, H);
    for (let x = 0; x <= W; x += 3) {
      ctx.lineTo(x, H * w.y + Math.sin(x * w.freq + t * w.speed + w.offset) * w.amp);
    }
    ctx.lineTo(W, H); ctx.closePath();
    ctx.fillStyle = w.color; ctx.fill();
  }

  (function loop() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    waves.forEach(drawWave);
    t += 1;
    requestAnimationFrame(loop);
  })();
})();

// ─── Scroll reveal ────────────────────────────────────────────────────────────

(function initReveal() {
  const obs = new IntersectionObserver((entries) => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); } });
  }, { threshold: 0.1 });

  document.querySelectorAll('.service-card, .gig-card, .about-grid, .booking-wrap').forEach(el => {
    el.classList.add('reveal');
    obs.observe(el);
  });
})();

// ─── Carousel builder ─────────────────────────────────────────────────────────

/**
 * buildCarousel(config)
 *
 * config.trackEl    — the .carousel-track element
 * config.dotsEl     — the .carousel-dots element
 * config.arrowLeft  — left arrow button
 * config.arrowRight — right arrow button
 * config.slides     — array of DOM elements (already built)
 * config.visibleCount — how many slides are fully visible at once (used for arrow logic)
 */
function buildCarousel({ trackEl, dotsEl, arrowLeft, arrowRight, slides }) {
  if (!slides.length) return;

  slides.forEach(s => trackEl.appendChild(s));

  let current = 0;
  const total = slides.length;

  // Build dots
  slides.forEach((_, i) => {
    const dot = document.createElement('div');
    dot.className = 'dot' + (i === 0 ? ' active' : '');
    dot.addEventListener('click', () => goTo(i));
    dotsEl.appendChild(dot);
  });

  function goTo(idx) {
    current = Math.max(0, Math.min(idx, total - 1));
    const slide = slides[current];
    const trackLeft = trackEl.getBoundingClientRect().left;
    const slideLeft = slide.getBoundingClientRect().left;
    const offset = parseFloat(trackEl.style.transform.replace('translateX(', '') || '0');
    const newOffset = offset - (slideLeft - trackLeft) + (trackEl.parentElement.offsetWidth / 2) - (slide.offsetWidth / 2);
    trackEl.style.transform = `translateX(${newOffset}px)`;

    slides.forEach((s, i) => s.classList.toggle('is-active', i === current));
    dotsEl.querySelectorAll('.dot').forEach((d, i) => d.classList.toggle('active', i === current));
    arrowLeft.disabled  = current === 0;
    arrowRight.disabled = current === total - 1;
  }

  arrowLeft.addEventListener('click',  () => goTo(current - 1));
  arrowRight.addEventListener('click', () => goTo(current + 1));

  // Drag / swipe support
  let dragStartX = 0, dragging = false, dragOffset = 0;

  trackEl.parentElement.addEventListener('mousedown',  e => { dragging = true; dragStartX = e.clientX; });
  trackEl.parentElement.addEventListener('touchstart', e => { dragging = true; dragStartX = e.touches[0].clientX; }, { passive: true });

  window.addEventListener('mousemove', e => {
    if (!dragging) return;
    dragOffset = e.clientX - dragStartX;
  });
  window.addEventListener('touchmove', e => {
    if (!dragging) return;
    dragOffset = e.touches[0].clientX - dragStartX;
  }, { passive: true });

  function endDrag() {
    if (!dragging) return;
    dragging = false;
    if (dragOffset < -60) goTo(current + 1);
    else if (dragOffset > 60) goTo(current - 1);
    else goTo(current);
    dragOffset = 0;
  }
  window.addEventListener('mouseup',   endDrag);
  window.addEventListener('touchend',  endDrag);

  // Init
  requestAnimationFrame(() => goTo(0));
  arrowLeft.disabled = true;
}

// ─── Video lightbox ───────────────────────────────────────────────────────────

const lightbox     = document.getElementById('videoLightbox');
const lightboxVid  = document.getElementById('lightboxVideo');
const lightboxClose = document.getElementById('lightboxClose');

function openLightbox(src) {
  lightboxVid.src = src;
  lightbox.classList.add('open');
  lightboxVid.play();
}

function closeLightbox() {
  lightbox.classList.remove('open');
  lightboxVid.pause();
  lightboxVid.src = '';
}

lightboxClose.addEventListener('click', closeLightbox);
lightbox.addEventListener('click', e => { if (e.target === lightbox) closeLightbox(); });
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeLightbox(); });

// ─── Dynamic asset loader (reads manifest.json) ───────────────────────────────

fetch('assets/manifest.json')
  .then(r => r.json())
  .then(manifest => {

    // ── HERO background (random pick from assets/hero/) ──────────────────────
    // To change: add/remove images in assets/hero/, re-run generate-manifest.js
    const heroFiles = manifest['hero'] || [];
    if (heroFiles.length) {
      const heroBg  = document.getElementById('heroBg');
      const heroSrc = pickRandom(heroFiles);
      const img = new Image();
      img.onload = () => {
        heroBg.style.backgroundImage = `url('${heroSrc}')`;
        requestAnimationFrame(() => heroBg.classList.add('loaded'));
      };
      img.src = heroSrc;
    }

    // ── ABOUT photo (random pick from assets/about/) ─────────────────────────
    // To change: add/remove images in assets/about/, re-run generate-manifest.js
    const aboutFiles = manifest['about'] || [];
    if (aboutFiles.length) {
      const frame = document.getElementById('aboutImgFrame');
      const src   = pickRandom(aboutFiles);
      frame.innerHTML = '';
      const img = document.createElement('img');
      img.src = src;
      img.alt = 'DJ Sharkboy performing';
      frame.appendChild(img);
    }

    // ── PHOTO CAROUSEL (all from assets/gallery-photos/) ─────────────────────
    // To change: add/remove images in assets/gallery-photos/, re-run generate-manifest.js
    const photoFiles = manifest['gallery-photos'] || [];
    if (photoFiles.length) {
      const slides = photoFiles.map(src => {
        const div = document.createElement('div');
        div.className = 'photo-slide';
        const img = document.createElement('img');
        img.src = src;
        img.alt = '';
        img.loading = 'lazy';
        div.appendChild(img);
        return div;
      });

      buildCarousel({
        trackEl:    document.getElementById('photoTrack'),
        dotsEl:     document.getElementById('photoDots'),
        arrowLeft:  document.getElementById('photoArrowLeft'),
        arrowRight: document.getElementById('photoArrowRight'),
        slides,
      });
    }

    // ── VIDEO REEL (all from assets/gallery-videos/) ──────────────────────────
    // To change: add/remove videos in assets/gallery-videos/, re-run generate-manifest.js
    const videoFiles = manifest['gallery-videos'] || [];
    if (videoFiles.length) {
      const slides = videoFiles.map(src => {
        const div = document.createElement('div');
        div.className = 'video-slide';

        // Silent preview video (autoplay muted for thumbnail feel)
        const vid = document.createElement('video');
        vid.src = src;
        vid.muted = true;
        vid.loop  = true;
        vid.playsInline = true;
        vid.preload = 'metadata';

        // Play silently on hover for preview
        div.addEventListener('mouseenter', () => vid.play());
        div.addEventListener('mouseleave', () => { vid.pause(); vid.currentTime = 0; });

        // Play button overlay
        const overlay = document.createElement('div');
        overlay.className = 'video-play-btn';
        const btn = document.createElement('span');
        btn.innerHTML = '&#9654;';
        overlay.appendChild(btn);

        // Click to open in lightbox fullscreen
        div.addEventListener('click', () => openLightbox(src));

        div.appendChild(vid);
        div.appendChild(overlay);
        return div;
      });

      buildCarousel({
        trackEl:    document.getElementById('videoTrack'),
        dotsEl:     document.getElementById('videoDots'),
        arrowLeft:  document.getElementById('videoArrowLeft'),
        arrowRight: document.getElementById('videoArrowRight'),
        slides,
      });
    }

  })
  .catch(err => console.warn('Could not load manifest.json — run generate-manifest.js first.', err));

// ─── Booking form (mailto fallback) ──────────────────────────────────────────

document.getElementById('bookingForm').addEventListener('submit', function (e) {
  e.preventDefault();
  const d = new FormData(this);
  const subject = encodeURIComponent('Booking Enquiry – ' + d.get('eventType'));
  const body    = encodeURIComponent(
    `Name: ${d.get('name')}\nEmail: ${d.get('email')}\nEvent: ${d.get('eventType')}\nDate: ${d.get('eventDate')}\nService: ${d.get('service')}\n\nDetails:\n${d.get('message')}`
  );
  window.location.href = `mailto:sharkboyrecords@gmail.com?subject=${subject}&body=${body}`;
});
